/**
 * WordDash'in kelime havuzu. Bilinçli olarak ÇEŞİTLİ uzunlukta (2-10 harf)
 * VE ARTAN ZORLUKTA sıralı: levels.ts bu diziyi index sırasıyla okuduğu
 * için, dizideki sıra = oyundaki zorluk eğrisi. En kısa/en yaygın
 * kelimeler baştaki seviyelerde, en uzun/az yaygın kelimeler sondaki
 * seviyelerde -- "çok kolaydan çok zora" ilerleme buradan geliyor.
 *
 * Yeni kelime eklerken TEK KURAL: doğru uzunluk grubunun içine, harf
 * sayısına göre ekle. Grup içi sıra önemsiz ama gruplar arası sıra =
 * zorluk eğrisi, o yüzden 5 harfli bir kelimeyi 7 harfliler grubuna
 * koymak eğriyi bozar.
 */
export interface WordEntry {
  word: string;
  tr: string;
}

export const WORD_LIST: WordEntry[] = [
  // 2 harf -- çok kolay
  { word: 'go', tr: 'git' },
  { word: 'up', tr: 'yukarı' },
  { word: 'no', tr: 'hayır' },
  { word: 'we', tr: 'biz' },
  { word: 'me', tr: 'ben' },
  { word: 'hi', tr: 'merhaba' },
  { word: 'do', tr: 'yapmak' },
  { word: 'in', tr: 'içinde' },
  { word: 'on', tr: 'üstünde' },

  // 3 harf
  { word: 'cat', tr: 'kedi' },
  { word: 'dog', tr: 'köpek' },
  { word: 'sun', tr: 'güneş' },
  { word: 'cup', tr: 'fincan' },
  { word: 'ear', tr: 'kulak' },
  { word: 'key', tr: 'anahtar' },
  { word: 'pen', tr: 'kalem' },
  { word: 'box', tr: 'kutu' },
  { word: 'car', tr: 'araba' },
  { word: 'bus', tr: 'otobüs' },
  { word: 'egg', tr: 'yumurta' },
  { word: 'cow', tr: 'inek' },
  { word: 'hat', tr: 'şapka' },
  { word: 'map', tr: 'harita' },
  { word: 'sky', tr: 'gökyüzü' },
  { word: 'arm', tr: 'kol' },
  { word: 'leg', tr: 'bacak' },
  { word: 'eye', tr: 'göz' },
  { word: 'bed', tr: 'yatak' },
  { word: 'toy', tr: 'oyuncak' },

  // 4 harf
  { word: 'book', tr: 'kitap' },
  { word: 'fish', tr: 'balık' },
  { word: 'bird', tr: 'kuş' },
  { word: 'moon', tr: 'ay' },
  { word: 'star', tr: 'yıldız' },
  { word: 'tree', tr: 'ağaç' },
  { word: 'lion', tr: 'aslan' },
  { word: 'rose', tr: 'gül' },
  { word: 'milk', tr: 'süt' },
  { word: 'cake', tr: 'pasta' },
  { word: 'door', tr: 'kapı' },
  { word: 'hand', tr: 'el' },
  { word: 'foot', tr: 'ayak' },
  { word: 'road', tr: 'yol' },
  { word: 'rain', tr: 'yağmur' },
  { word: 'snow', tr: 'kar' },
  { word: 'fire', tr: 'ateş' },
  { word: 'gold', tr: 'altın' },
  { word: 'ship', tr: 'gemi' },
  { word: 'bear', tr: 'ayı' },
  { word: 'wolf', tr: 'kurt' },
  { word: 'duck', tr: 'ördek' },
  { word: 'gift', tr: 'hediye' },
  { word: 'king', tr: 'kral' },
  { word: 'ball', tr: 'top' },
  { word: 'love', tr: 'aşk' },
  { word: 'time', tr: 'zaman' },
  { word: 'word', tr: 'kelime' },
  { word: 'game', tr: 'oyun' },
  { word: 'cold', tr: 'soğuk' },

  // 5 harf
  { word: 'house', tr: 'ev' },
  { word: 'water', tr: 'su' },
  { word: 'table', tr: 'masa' },
  { word: 'apple', tr: 'elma' },
  { word: 'happy', tr: 'mutlu' },
  { word: 'tiger', tr: 'kaplan' },
  { word: 'cloud', tr: 'bulut' },
  { word: 'grape', tr: 'üzüm' },
  { word: 'bread', tr: 'ekmek' },
  { word: 'chair', tr: 'sandalye' },
  { word: 'night', tr: 'gece' },
  { word: 'light', tr: 'ışık' },
  { word: 'music', tr: 'müzik' },
  { word: 'river', tr: 'nehir' },
  { word: 'horse', tr: 'at' },
  { word: 'sheep', tr: 'koyun' },
  { word: 'mouse', tr: 'fare' },
  { word: 'snake', tr: 'yılan' },
  { word: 'plant', tr: 'bitki' },
  { word: 'green', tr: 'yeşil' },
  { word: 'sugar', tr: 'şeker' },
  { word: 'honey', tr: 'bal' },
  { word: 'lemon', tr: 'limon' },
  { word: 'heart', tr: 'kalp' },
  { word: 'ocean', tr: 'okyanus' },
  { word: 'money', tr: 'para' },
  { word: 'queen', tr: 'kraliçe' },
  { word: 'dream', tr: 'rüya' },
  { word: 'smile', tr: 'gülümseme' },
  { word: 'world', tr: 'dünya' },
  { word: 'beach', tr: 'kumsal' },

  // 6 harf -- orta
  { word: 'garden', tr: 'bahçe' },
  { word: 'window', tr: 'pencere' },
  { word: 'animal', tr: 'hayvan' },
  { word: 'forest', tr: 'orman' },
  { word: 'flower', tr: 'çiçek' },
  { word: 'family', tr: 'aile' },
  { word: 'friend', tr: 'arkadaş' },
  { word: 'banana', tr: 'muz' },
  { word: 'rabbit', tr: 'tavşan' },
  { word: 'guitar', tr: 'gitar' },
  { word: 'orange', tr: 'portakal' },
  { word: 'yellow', tr: 'sarı' },
  { word: 'summer', tr: 'yaz' },
  { word: 'winter', tr: 'kış' },
  { word: 'school', tr: 'okul' },
  { word: 'doctor', tr: 'doktor' },
  { word: 'coffee', tr: 'kahve' },
  { word: 'cheese', tr: 'peynir' },
  { word: 'mother', tr: 'anne' },
  { word: 'father', tr: 'baba' },
  { word: 'sister', tr: 'kız kardeş' },
  { word: 'bridge', tr: 'köprü' },
  { word: 'castle', tr: 'kale' },
  { word: 'island', tr: 'ada' },
  { word: 'planet', tr: 'gezegen' },
  { word: 'monkey', tr: 'maymun' },
  { word: 'spider', tr: 'örümcek' },
  { word: 'turtle', tr: 'kaplumbağa' },
  { word: 'pocket', tr: 'cep' },
  { word: 'basket', tr: 'sepet' },
  { word: 'jacket', tr: 'ceket' },
  { word: 'tomato', tr: 'domates' },
  { word: 'pencil', tr: 'kurşun kalem' },

  // 7 harf
  { word: 'kitchen', tr: 'mutfak' },
  { word: 'morning', tr: 'sabah' },
  { word: 'teacher', tr: 'öğretmen' },
  { word: 'student', tr: 'öğrenci' },
  { word: 'journey', tr: 'yolculuk' },
  { word: 'rainbow', tr: 'gökkuşağı' },
  { word: 'dolphin', tr: 'yunus' },
  { word: 'village', tr: 'köy' },
  { word: 'chicken', tr: 'tavuk' },
  { word: 'weather', tr: 'hava' },
  { word: 'holiday', tr: 'tatil' },
  { word: 'evening', tr: 'akşam' },
  { word: 'brother', tr: 'erkek kardeş' },
  { word: 'kingdom', tr: 'krallık' },
  { word: 'picture', tr: 'resim' },
  { word: 'library', tr: 'kütüphane' },
  { word: 'country', tr: 'ülke' },
  { word: 'monster', tr: 'canavar' },
  { word: 'penguin', tr: 'penguen' },
  { word: 'giraffe', tr: 'zürafa' },
  { word: 'thunder', tr: 'gök gürültüsü' },
  { word: 'diamond', tr: 'elmas' },
  { word: 'science', tr: 'bilim' },
  { word: 'history', tr: 'tarih' },
  { word: 'freedom', tr: 'özgürlük' },

  // 8 harf -- zor
  { word: 'mountain', tr: 'dağ' },
  { word: 'elephant', tr: 'fil' },
  { word: 'computer', tr: 'bilgisayar' },
  { word: 'umbrella', tr: 'şemsiye' },
  { word: 'princess', tr: 'prenses' },
  { word: 'dinosaur', tr: 'dinozor' },
  { word: 'hospital', tr: 'hastane' },
  { word: 'birthday', tr: 'doğum günü' },
  { word: 'sandwich', tr: 'sandviç' },
  { word: 'airplane', tr: 'uçak' },
  { word: 'triangle', tr: 'üçgen' },
  { word: 'mushroom', tr: 'mantar' },
  { word: 'squirrel', tr: 'sincap' },
  { word: 'kangaroo', tr: 'kanguru' },
  { word: 'building', tr: 'bina' },
  { word: 'treasure', tr: 'hazine' },
  { word: 'sunshine', tr: 'gün ışığı' },
  { word: 'notebook', tr: 'defter' },
  { word: 'scissors', tr: 'makas' },
  { word: 'football', tr: 'futbol' },
  { word: 'baseball', tr: 'beyzbol' },
  { word: 'mosquito', tr: 'sivrisinek' },

  // 9 harf -- çok zor
  { word: 'butterfly', tr: 'kelebek' },
  { word: 'telephone', tr: 'telefon' },
  { word: 'chocolate', tr: 'çikolata' },
  { word: 'newspaper', tr: 'gazete' },
  { word: 'wonderful', tr: 'harika' },
  { word: 'beautiful', tr: 'güzel' },
  { word: 'adventure', tr: 'macera' },
  { word: 'dangerous', tr: 'tehlikeli' },
  { word: 'crocodile', tr: 'timsah' },
  { word: 'pineapple', tr: 'ananas' },
  { word: 'waterfall', tr: 'şelale' },
  { word: 'chemistry', tr: 'kimya' },
  { word: 'education', tr: 'eğitim' },
  { word: 'furniture', tr: 'mobilya' },
  { word: 'geography', tr: 'coğrafya' },
  { word: 'ambulance', tr: 'ambulans' },
  { word: 'delicious', tr: 'lezzetli' },
  { word: 'breakfast', tr: 'kahvaltı' },
  { word: 'orchestra', tr: 'orkestra' },
  { word: 'hamburger', tr: 'hamburger' },

  // 10 harf -- uzman
  { word: 'basketball', tr: 'basketbol' },
  { word: 'strawberry', tr: 'çilek' },
  { word: 'helicopter', tr: 'helikopter' },
  { word: 'technology', tr: 'teknoloji' },
  { word: 'restaurant', tr: 'restoran' },
  { word: 'television', tr: 'televizyon' },
  { word: 'watermelon', tr: 'karpuz' },
  { word: 'dictionary', tr: 'sözlük' },
];
