/**
 * WordDash'in kelime içeriği: KONU PAKETLERİ.
 *
 * v2'de tek düz bir liste vardı (198 kelime) ve bitince başa dönüyordu --
 * yani oyunun geri kalanı (100. seviyeye kadar giden rütbeler, sandıklar,
 * rozetler) içerikten kat kat uzundu. Oyuncu bir haftada her şeyi görüp
 * aynı kelimeleri tekrar çözmeye başlıyordu.
 *
 * v3: kelimeler KONUYA göre paketlenmiş. Bunun üç faydası var:
 *   1. Hacim -- 1000+ kelime, tekrara düşmeden aylarca oynanış.
 *   2. Görünür hedef -- oyuncu "Hayvanlar 12/64" görüyor, sonsuz bir
 *      listede yüzmüyor. Paket bitirmek somut bir başarı.
 *   3. Öğrenme değeri -- ilgili kelimeler bir arada öğrenildiğinde akılda
 *      daha iyi kalıyor; oyunun dil öğretme iddiası ancak böyle ciddiye
 *      alınabilir.
 *
 * PAKET SIRASI = ZORLUK EĞRİSİ. levels.ts paketleri bu sırayla, her paketin
 * içindeki kelimeleri de dizideki sırayla okuyor. Paket içindeki sıra kısa
 * kelimeden uzuna doğru.
 *
 * KELİME EKLEME KURALLARI (scripts/check-words.mjs bunları mekanik olarak
 * doğruluyor, `npm run check:words`):
 *   - yalnızca küçük harf a-z (tekerlek başka karakteri çizemez)
 *   - 2-9 harf (10+ harf tekerlekte okunmuyor)
 *   - hiçbir kelime iki pakette birden geçmeyecek
 *   - Türkçe karşılık TEK ve NET olmalı: kelimenin en yaygın anlamı.
 *     Birden çok anlamı olan kelimede oyuncu ipucundan cevabı bulamıyorsa
 *     o kelime buraya ait değil.
 */

export interface WordEntry {
  word: string;
  tr: string;
}

export interface WordPack {
  id: string;
  /** Paket adı -- arayüz dili TR iken gösterilir. */
  name: string;
  nameEn: string;
  icon: string;
  /** Kısa tanıtım satırı (paket haritasında kartın altında). */
  blurb: string;
  blurbEn: string;
  words: WordEntry[];
}

export const WORD_PACKS: WordPack[] = [
  {
    id: 'temel',
    name: 'Temel',
    nameEn: 'Basics',
    icon: '🌱',
    blurb: 'Her cümlede geçen çekirdek kelimeler',
    blurbEn: 'The core words that appear in every sentence',
    words: [
      { word: 'go', tr: 'git' },
      { word: 'up', tr: 'yukarı' },
      { word: 'no', tr: 'hayır' },
      { word: 'we', tr: 'biz' },
      { word: 'me', tr: 'ben' },
      { word: 'hi', tr: 'merhaba' },
      { word: 'do', tr: 'yapmak' },
      { word: 'in', tr: 'içinde' },
      { word: 'on', tr: 'üstünde' },
      { word: 'it', tr: 'o (nesne)' },
      { word: 'at', tr: 'de, da' },
      { word: 'my', tr: 'benim' },
      { word: 'he', tr: 'o (erkek)' },
      { word: 'if', tr: 'eğer' },
      { word: 'or', tr: 'veya' },
      { word: 'yes', tr: 'evet' },
      { word: 'and', tr: 've' },
      { word: 'but', tr: 'ama' },
      { word: 'now', tr: 'şimdi' },
      { word: 'who', tr: 'kim' },
      { word: 'how', tr: 'nasıl' },
      { word: 'why', tr: 'neden' },
      { word: 'one', tr: 'bir' },
      { word: 'two', tr: 'iki' },
      { word: 'six', tr: 'altı' },
      { word: 'ten', tr: 'on' },
      { word: 'she', tr: 'o (kadın)' },
      { word: 'you', tr: 'sen' },
      { word: 'her', tr: 'onun (kadın)' },
      { word: 'his', tr: 'onun (erkek)' },
      { word: 'our', tr: 'bizim' },
      { word: 'not', tr: 'değil' },
      { word: 'too', tr: 'de, fazla' },
      { word: 'out', tr: 'dışarı' },
      { word: 'for', tr: 'için' },
      { word: 'this', tr: 'bu' },
      { word: 'that', tr: 'şu' },
      { word: 'here', tr: 'burada' },
      { word: 'when', tr: 'ne zaman' },
      { word: 'what', tr: 'ne' },
      { word: 'some', tr: 'bazı' },
      { word: 'many', tr: 'birçok' },
      { word: 'more', tr: 'daha fazla' },
      { word: 'most', tr: 'en çok' },
      { word: 'very', tr: 'çok' },
      { word: 'also', tr: 'ayrıca' },
      { word: 'than', tr: 'göre' },
      { word: 'then', tr: 'sonra' },
      { word: 'they', tr: 'onlar' },
      { word: 'just', tr: 'sadece' },
      { word: 'only', tr: 'yalnızca' },
      { word: 'over', tr: 'üzerinde' },
      { word: 'same', tr: 'aynı' },
      { word: 'with', tr: 'ile' },
      { word: 'into', tr: 'içine' },
      { word: 'from', tr: 'den, dan' },
      { word: 'four', tr: 'dört' },
      { word: 'five', tr: 'beş' },
      { word: 'nine', tr: 'dokuz' },
      { word: 'zero', tr: 'sıfır' },
      { word: 'three', tr: 'üç' },
      { word: 'seven', tr: 'yedi' },
      { word: 'eight', tr: 'sekiz' },
      { word: 'there', tr: 'orada' },
      { word: 'where', tr: 'nerede' },
      { word: 'which', tr: 'hangi' },
      { word: 'about', tr: 'hakkında' },
      { word: 'other', tr: 'diğer' },
      { word: 'every', tr: 'her' },
      { word: 'again', tr: 'tekrar' },
      { word: 'under', tr: 'altında' },
      { word: 'between', tr: 'arasında' },
      { word: 'because', tr: 'çünkü' },
      { word: 'without', tr: 'olmadan' },
      { word: 'together', tr: 'birlikte' },
    ],
  },

  {
    id: 'yiyecek',
    name: 'Yiyecek & İçecek',
    nameEn: 'Food & Drink',
    icon: '🍎',
    blurb: 'Mutfak, market ve restoran kelimeleri',
    blurbEn: 'Kitchen, grocery and restaurant words',
    words: [
      { word: 'egg', tr: 'yumurta' },
      { word: 'tea', tr: 'çay' },
      { word: 'jam', tr: 'reçel' },
      { word: 'pie', tr: 'turta' },
      { word: 'oil', tr: 'yağ' },
      { word: 'nut', tr: 'kuruyemiş' },
      { word: 'ham', tr: 'jambon' },
      { word: 'milk', tr: 'süt' },
      { word: 'rice', tr: 'pirinç' },
      { word: 'meat', tr: 'et' },
      { word: 'cake', tr: 'pasta' },
      { word: 'soup', tr: 'çorba' },
      { word: 'salt', tr: 'tuz' },
      { word: 'corn', tr: 'mısır' },
      { word: 'bean', tr: 'fasulye' },
      { word: 'pear', tr: 'armut' },
      { word: 'plum', tr: 'erik' },
      { word: 'mint', tr: 'nane' },
      { word: 'herb', tr: 'ot, bitki' },
      { word: 'wine', tr: 'şarap' },
      { word: 'beef', tr: 'dana eti' },
      { word: 'bread', tr: 'ekmek' },
      { word: 'apple', tr: 'elma' },
      { word: 'sugar', tr: 'şeker' },
      { word: 'water', tr: 'su' },
      { word: 'juice', tr: 'meyve suyu' },
      { word: 'honey', tr: 'bal' },
      { word: 'olive', tr: 'zeytin' },
      { word: 'lemon', tr: 'limon' },
      { word: 'peach', tr: 'şeftali' },
      { word: 'grape', tr: 'üzüm' },
      { word: 'onion', tr: 'soğan' },
      { word: 'melon', tr: 'kavun' },
      { word: 'salad', tr: 'salata' },
      { word: 'sauce', tr: 'sos' },
      { word: 'cream', tr: 'krema' },
      { word: 'candy', tr: 'şekerleme' },
      { word: 'flour', tr: 'un' },
      { word: 'toast', tr: 'tost' },
      { word: 'syrup', tr: 'şurup' },
      { word: 'berry', tr: 'çilek türü meyve' },
      { word: 'snack', tr: 'atıştırmalık' },
      { word: 'steak', tr: 'biftek' },
      { word: 'cheese', tr: 'peynir' },
      { word: 'butter', tr: 'tereyağı' },
      { word: 'coffee', tr: 'kahve' },
      { word: 'tomato', tr: 'domates' },
      { word: 'potato', tr: 'patates' },
      { word: 'carrot', tr: 'havuç' },
      { word: 'orange', tr: 'portakal' },
      { word: 'banana', tr: 'muz' },
      { word: 'garlic', tr: 'sarımsak' },
      { word: 'pepper', tr: 'biber' },
      { word: 'walnut', tr: 'ceviz' },
      { word: 'cherry', tr: 'kiraz' },
      { word: 'yogurt', tr: 'yoğurt' },
      { word: 'dinner', tr: 'akşam yemeği' },
      { word: 'pastry', tr: 'hamur işi' },
      { word: 'noodle', tr: 'erişte' },
      { word: 'almond', tr: 'badem' },
      { word: 'muffin', tr: 'kek' },
      { word: 'chicken', tr: 'tavuk' },
      { word: 'dessert', tr: 'tatlı' },
      { word: 'sausage', tr: 'sosis' },
      { word: 'biscuit', tr: 'bisküvi' },
      { word: 'apricot', tr: 'kayısı' },
      { word: 'popcorn', tr: 'patlamış mısır' },
      { word: 'seafood', tr: 'deniz ürünü' },
      { word: 'cabbage', tr: 'lahana' },
      { word: 'lettuce', tr: 'marul' },
      { word: 'pumpkin', tr: 'balkabağı' },
      { word: 'spinach', tr: 'ıspanak' },
      { word: 'vinegar', tr: 'sirke' },
      { word: 'eggplant', tr: 'patlıcan' },
      { word: 'sandwich', tr: 'sandviç' },
      { word: 'cucumber', tr: 'salatalık' },
      { word: 'breakfast', tr: 'kahvaltı' },
      { word: 'chocolate', tr: 'çikolata' },
      { word: 'pineapple', tr: 'ananas' },
      { word: 'raspberry', tr: 'ahududu' },
    ],
  },

  {
    id: 'hayvanlar',
    name: 'Hayvanlar',
    nameEn: 'Animals',
    icon: '🐾',
    blurb: 'Evcil hayvanlardan vahşi doğaya',
    blurbEn: 'From pets to wildlife',
    words: [
      { word: 'cat', tr: 'kedi' },
      { word: 'dog', tr: 'köpek' },
      { word: 'cow', tr: 'inek' },
      { word: 'pig', tr: 'domuz' },
      { word: 'fox', tr: 'tilki' },
      { word: 'owl', tr: 'baykuş' },
      { word: 'ant', tr: 'karınca' },
      { word: 'bee', tr: 'arı' },
      { word: 'bat', tr: 'yarasa' },
      { word: 'hen', tr: 'tavuk (dişi)' },
      { word: 'ram', tr: 'koç' },
      { word: 'bird', tr: 'kuş' },
      { word: 'fish', tr: 'balık' },
      { word: 'lion', tr: 'aslan' },
      { word: 'bear', tr: 'ayı' },
      { word: 'wolf', tr: 'kurt' },
      { word: 'deer', tr: 'geyik' },
      { word: 'frog', tr: 'kurbağa' },
      { word: 'duck', tr: 'ördek' },
      { word: 'goat', tr: 'keçi' },
      { word: 'crab', tr: 'yengeç' },
      { word: 'seal', tr: 'fok' },
      { word: 'mole', tr: 'köstebek' },
      { word: 'swan', tr: 'kuğu' },
      { word: 'crow', tr: 'karga' },
      { word: 'lamb', tr: 'kuzu' },
      { word: 'mule', tr: 'katır' },
      { word: 'toad', tr: 'kara kurbağası' },
      { word: 'dove', tr: 'güvercin' },
      { word: 'worm', tr: 'solucan' },
      { word: 'horse', tr: 'at' },
      { word: 'sheep', tr: 'koyun' },
      { word: 'tiger', tr: 'kaplan' },
      { word: 'mouse', tr: 'fare' },
      { word: 'snake', tr: 'yılan' },
      { word: 'whale', tr: 'balina' },
      { word: 'shark', tr: 'köpekbalığı' },
      { word: 'eagle', tr: 'kartal' },
      { word: 'zebra', tr: 'zebra' },
      { word: 'camel', tr: 'deve' },
      { word: 'goose', tr: 'kaz' },
      { word: 'moose', tr: 'sığın geyiği' },
      { word: 'snail', tr: 'salyangoz' },
      { word: 'koala', tr: 'koala' },
      { word: 'robin', tr: 'kızılgerdan' },
      { word: 'hyena', tr: 'sırtlan' },
      { word: 'otter', tr: 'su samuru' },
      { word: 'panda', tr: 'panda' },
      { word: 'hippo', tr: 'su aygırı' },
      { word: 'rhino', tr: 'gergedan' },
      { word: 'llama', tr: 'lama' },
      { word: 'stork', tr: 'leylek' },
      { word: 'monkey', tr: 'maymun' },
      { word: 'rabbit', tr: 'tavşan' },
      { word: 'donkey', tr: 'eşek' },
      { word: 'turtle', tr: 'kaplumbağa' },
      { word: 'parrot', tr: 'papağan' },
      { word: 'spider', tr: 'örümcek' },
      { word: 'salmon', tr: 'somon' },
      { word: 'beetle', tr: 'böcek' },
      { word: 'falcon', tr: 'şahin' },
      { word: 'kitten', tr: 'yavru kedi' },
      { word: 'insect', tr: 'böcek' },
      { word: 'lizard', tr: 'kertenkele' },
      { word: 'turkey', tr: 'hindi' },
      { word: 'badger', tr: 'porsuk' },
      { word: 'cheeta', tr: 'çita' },
      { word: 'giraffe', tr: 'zürafa' },
      { word: 'dolphin', tr: 'yunus' },
      { word: 'penguin', tr: 'penguen' },
      { word: 'rooster', tr: 'horoz' },
      { word: 'buffalo', tr: 'bufalo' },
      { word: 'leopard', tr: 'leopar' },
      { word: 'hamster', tr: 'hamster' },
      { word: 'peacock', tr: 'tavus kuşu' },
      { word: 'octopus', tr: 'ahtapot' },
      { word: 'seagull', tr: 'martı' },
      { word: 'elephant', tr: 'fil' },
      { word: 'squirrel', tr: 'sincap' },
      { word: 'kangaroo', tr: 'kanguru' },
      { word: 'reindeer', tr: 'ren geyiği' },
      { word: 'butterfly', tr: 'kelebek' },
      { word: 'crocodile', tr: 'timsah' },
    ],
  },

  {
    id: 'ev',
    name: 'Ev & Eşya',
    nameEn: 'Home & Objects',
    icon: '🏠',
    blurb: 'Evin içindeki her şey',
    blurbEn: 'Everything inside the house',
    words: [
      { word: 'bed', tr: 'yatak' },
      { word: 'cup', tr: 'fincan' },
      { word: 'box', tr: 'kutu' },
      { word: 'jar', tr: 'kavanoz' },
      { word: 'pot', tr: 'tencere' },
      { word: 'pan', tr: 'tava' },
      { word: 'fan', tr: 'vantilatör' },
      { word: 'mat', tr: 'paspas' },
      { word: 'rug', tr: 'kilim' },
      { word: 'key', tr: 'anahtar' },
      { word: 'mop', tr: 'yer paspası' },
      { word: 'tap', tr: 'musluk' },
      { word: 'door', tr: 'kapı' },
      { word: 'wall', tr: 'duvar' },
      { word: 'roof', tr: 'çatı' },
      { word: 'lamp', tr: 'lamba' },
      { word: 'sofa', tr: 'kanepe' },
      { word: 'desk', tr: 'çalışma masası' },
      { word: 'dish', tr: 'tabak' },
      { word: 'bowl', tr: 'kase' },
      { word: 'fork', tr: 'çatal' },
      { word: 'sink', tr: 'lavabo' },
      { word: 'soap', tr: 'sabun' },
      { word: 'oven', tr: 'fırın' },
      { word: 'comb', tr: 'tarak' },
      { word: 'vase', tr: 'vazo' },
      { word: 'seat', tr: 'oturak' },
      { word: 'gate', tr: 'bahçe kapısı' },
      { word: 'rope', tr: 'ip' },
      { word: 'tape', tr: 'bant' },
      { word: 'wood', tr: 'ahşap' },
      { word: 'iron', tr: 'ütü' },
      { word: 'lock', tr: 'kilit' },
      { word: 'nail', tr: 'çivi' },
      { word: 'chair', tr: 'sandalye' },
      { word: 'table', tr: 'masa' },
      { word: 'house', tr: 'ev' },
      { word: 'floor', tr: 'zemin' },
      { word: 'plate', tr: 'tabak' },
      { word: 'glass', tr: 'bardak' },
      { word: 'knife', tr: 'bıçak' },
      { word: 'spoon', tr: 'kaşık' },
      { word: 'clock', tr: 'saat' },
      { word: 'towel', tr: 'havlu' },
      { word: 'shelf', tr: 'raf' },
      { word: 'brush', tr: 'fırça' },
      { word: 'stove', tr: 'ocak' },
      { word: 'couch', tr: 'koltuk' },
      { word: 'broom', tr: 'süpürge' },
      { word: 'chest', tr: 'sandık' },
      { word: 'stair', tr: 'basamak' },
      { word: 'blind', tr: 'stor perde' },
      { word: 'window', tr: 'pencere' },
      { word: 'carpet', tr: 'halı' },
      { word: 'pillow', tr: 'yastık' },
      { word: 'basket', tr: 'sepet' },
      { word: 'fridge', tr: 'buzdolabı' },
      { word: 'mirror', tr: 'ayna' },
      { word: 'drawer', tr: 'çekmece' },
      { word: 'teapot', tr: 'demlik' },
      { word: 'candle', tr: 'mum' },
      { word: 'kettle', tr: 'kettle, su ısıtıcı' },
      { word: 'ladder', tr: 'merdiven' },
      { word: 'closet', tr: 'dolap' },
      { word: 'hanger', tr: 'askı' },
      { word: 'napkin', tr: 'peçete' },
      { word: 'bucket', tr: 'kova' },
      { word: 'kitchen', tr: 'mutfak' },
      { word: 'bedroom', tr: 'yatak odası' },
      { word: 'blanket', tr: 'battaniye' },
      { word: 'curtain', tr: 'perde' },
      { word: 'cushion', tr: 'minder' },
      { word: 'cabinet', tr: 'dolap' },
      { word: 'freezer', tr: 'derin dondurucu' },
      { word: 'balcony', tr: 'balkon' },
      { word: 'ceiling', tr: 'tavan' },
      { word: 'bathroom', tr: 'banyo' },
      { word: 'doorbell', tr: 'kapı zili' },
      { word: 'wardrobe', tr: 'gardırop' },
      { word: 'armchair', tr: 'koltuk' },
      { word: 'furniture', tr: 'mobilya' },
    ],
  },

  {
    id: 'vucut',
    name: 'Vücut & Sağlık',
    nameEn: 'Body & Health',
    icon: '🫀',
    blurb: 'Vücudun parçaları, hastane ve sağlık',
    blurbEn: 'Body parts, hospital and health',
    words: [
      { word: 'eye', tr: 'göz' },
      { word: 'ear', tr: 'kulak' },
      { word: 'arm', tr: 'kol' },
      { word: 'leg', tr: 'bacak' },
      { word: 'lip', tr: 'dudak' },
      { word: 'hip', tr: 'kalça' },
      { word: 'jaw', tr: 'çene' },
      { word: 'rib', tr: 'kaburga' },
      { word: 'toe', tr: 'ayak parmağı' },
      { word: 'gum', tr: 'diş eti' },
      { word: 'hand', tr: 'el' },
      { word: 'head', tr: 'kafa' },
      { word: 'hair', tr: 'saç' },
      { word: 'foot', tr: 'ayak' },
      { word: 'face', tr: 'yüz' },
      { word: 'nose', tr: 'burun' },
      { word: 'neck', tr: 'boyun' },
      { word: 'back', tr: 'sırt' },
      { word: 'skin', tr: 'deri' },
      { word: 'bone', tr: 'kemik' },
      { word: 'knee', tr: 'diz' },
      { word: 'chin', tr: 'çene ucu' },
      { word: 'heel', tr: 'topuk' },
      { word: 'vein', tr: 'damar' },
      { word: 'lung', tr: 'akciğer' },
      { word: 'palm', tr: 'avuç içi' },
      { word: 'pain', tr: 'ağrı' },
      { word: 'pill', tr: 'hap' },
      { word: 'mouth', tr: 'ağız' },
      { word: 'teeth', tr: 'dişler' },
      { word: 'heart', tr: 'kalp' },
      { word: 'brain', tr: 'beyin' },
      { word: 'pulse', tr: 'nabız' },
      { word: 'thumb', tr: 'başparmak' },
      { word: 'blood', tr: 'kan' },
      { word: 'elbow', tr: 'dirsek' },
      { word: 'ankle', tr: 'ayak bileği' },
      { word: 'waist', tr: 'bel' },
      { word: 'wrist', tr: 'el bileği' },
      { word: 'spine', tr: 'omurga' },
      { word: 'liver', tr: 'karaciğer' },
      { word: 'nurse', tr: 'hemşire' },
      { word: 'virus', tr: 'virüs' },
      { word: 'cough', tr: 'öksürük' },
      { word: 'fever', tr: 'ateş (hastalık)' },
      { word: 'wound', tr: 'yara' },
      { word: 'finger', tr: 'parmak' },
      { word: 'muscle', tr: 'kas' },
      { word: 'throat', tr: 'boğaz' },
      { word: 'tongue', tr: 'dil (organ)' },
      { word: 'kidney', tr: 'böbrek' },
      { word: 'doctor', tr: 'doktor' },
      { word: 'health', tr: 'sağlık' },
      { word: 'injury', tr: 'yaralanma' },
      { word: 'tablet', tr: 'tablet ilaç' },
      { word: 'breath', tr: 'nefes' },
      { word: 'stomach', tr: 'mide' },
      { word: 'patient', tr: 'hasta' },
      { word: 'illness', tr: 'hastalık' },
      { word: 'dentist', tr: 'diş hekimi' },
      { word: 'allergy', tr: 'alerji' },
      { word: 'surgery', tr: 'ameliyat' },
      { word: 'eyebrow', tr: 'kaş' },
      { word: 'stretch', tr: 'esnetmek' },
      { word: 'bandage', tr: 'bandaj' },
      { word: 'shoulder', tr: 'omuz' },
      { word: 'hospital', tr: 'hastane' },
      { word: 'forehead', tr: 'alın' },
      { word: 'pharmacy', tr: 'eczane' },
      { word: 'medicine', tr: 'ilaç' },
      { word: 'headache', tr: 'baş ağrısı' },
    ],
  },

  {
    id: 'aile',
    name: 'Aile & İnsanlar',
    nameEn: 'Family & People',
    icon: '👨‍👩‍👧',
    blurb: 'Akrabalar, arkadaşlar, insanlar',
    blurbEn: 'Relatives, friends, people',
    words: [
      { word: 'mom', tr: 'anne' },
      { word: 'dad', tr: 'baba' },
      { word: 'son', tr: 'oğul' },
      { word: 'boy', tr: 'erkek çocuk' },
      { word: 'man', tr: 'adam' },
      { word: 'kid', tr: 'çocuk' },
      { word: 'guy', tr: 'herif, adam' },
      { word: 'baby', tr: 'bebek' },
      { word: 'girl', tr: 'kız' },
      { word: 'wife', tr: 'eş (kadın)' },
      { word: 'aunt', tr: 'teyze, hala' },
      { word: 'twin', tr: 'ikiz' },
      { word: 'teen', tr: 'ergen' },
      { word: 'hero', tr: 'kahraman' },
      { word: 'lady', tr: 'hanımefendi' },
      { word: 'name', tr: 'isim' },
      { word: 'host', tr: 'ev sahibi' },
      { word: 'folk', tr: 'halk' },
      { word: 'uncle', tr: 'amca, dayı' },
      { word: 'niece', tr: 'yeğen (kız)' },
      { word: 'child', tr: 'çocuk' },
      { word: 'adult', tr: 'yetişkin' },
      { word: 'woman', tr: 'kadın' },
      { word: 'elder', tr: 'yaşlı' },
      { word: 'guest', tr: 'misafir' },
      { word: 'bride', tr: 'gelin' },
      { word: 'groom', tr: 'damat' },
      { word: 'crowd', tr: 'kalabalık' },
      { word: 'group', tr: 'grup' },
      { word: 'mother', tr: 'anne' },
      { word: 'father', tr: 'baba' },
      { word: 'sister', tr: 'kız kardeş' },
      { word: 'family', tr: 'aile' },
      { word: 'nephew', tr: 'yeğen (erkek)' },
      { word: 'spouse', tr: 'eş' },
      { word: 'couple', tr: 'çift' },
      { word: 'friend', tr: 'arkadaş' },
      { word: 'cousin', tr: 'kuzen' },
      { word: 'orphan', tr: 'yetim' },
      { word: 'person', tr: 'kişi' },
      { word: 'parent', tr: 'ebeveyn' },
      { word: 'single', tr: 'bekar' },
      { word: 'nation', tr: 'millet' },
      { word: 'people', tr: 'insanlar' },
      { word: 'brother', tr: 'erkek kardeş' },
      { word: 'husband', tr: 'eş (erkek)' },
      { word: 'grandma', tr: 'büyükanne' },
      { word: 'grandpa', tr: 'büyükbaba' },
      { word: 'partner', tr: 'ortak, partner' },
      { word: 'married', tr: 'evli' },
      { word: 'society', tr: 'toplum' },
      { word: 'daughter', tr: 'kız evlat' },
      { word: 'children', tr: 'çocuklar' },
      { word: 'relative', tr: 'akraba' },
      { word: 'ancestor', tr: 'ata, cet' },
      { word: 'roommate', tr: 'ev arkadaşı' },
      { word: 'neighbor', tr: 'komşu' },
    ],
  },

  {
    id: 'giyim',
    name: 'Giyim',
    nameEn: 'Clothing',
    icon: '👕',
    blurb: 'Kıyafetler, ayakkabılar, aksesuarlar',
    blurbEn: 'Clothes, shoes, accessories',
    words: [
      { word: 'hat', tr: 'şapka' },
      { word: 'cap', tr: 'kep' },
      { word: 'tie', tr: 'kravat' },
      { word: 'pin', tr: 'iğne' },
      { word: 'bag', tr: 'çanta' },
      { word: 'coat', tr: 'palto' },
      { word: 'sock', tr: 'çorap' },
      { word: 'suit', tr: 'takım elbise' },
      { word: 'belt', tr: 'kemer' },
      { word: 'boot', tr: 'bot' },
      { word: 'ring', tr: 'yüzük' },
      { word: 'silk', tr: 'ipek' },
      { word: 'wool', tr: 'yün' },
      { word: 'robe', tr: 'bornoz' },
      { word: 'veil', tr: 'duvak' },
      { word: 'vest', tr: 'yelek' },
      { word: 'gown', tr: 'uzun elbise' },
      { word: 'lace', tr: 'dantel' },
      { word: 'cuff', tr: 'manşet' },
      { word: 'shirt', tr: 'gömlek' },
      { word: 'dress', tr: 'elbise' },
      { word: 'jeans', tr: 'kot pantolon' },
      { word: 'shoes', tr: 'ayakkabılar' },
      { word: 'skirt', tr: 'etek' },
      { word: 'scarf', tr: 'atkı' },
      { word: 'glove', tr: 'eldiven' },
      { word: 'shawl', tr: 'şal' },
      { word: 'purse', tr: 'el çantası' },
      { word: 'pants', tr: 'pantolon' },
      { word: 'cloak', tr: 'pelerin' },
      { word: 'denim', tr: 'kot kumaşı' },
      { word: 'strap', tr: 'askı, kayış' },
      { word: 'jacket', tr: 'ceket' },
      { word: 'blouse', tr: 'bluz' },
      { word: 'sandal', tr: 'sandalet' },
      { word: 'wallet', tr: 'cüzdan' },
      { word: 'button', tr: 'düğme' },
      { word: 'zipper', tr: 'fermuar' },
      { word: 'pocket', tr: 'cep' },
      { word: 'tights', tr: 'külotlu çorap' },
      { word: 'mitten', tr: 'eldiven (parmaksız)' },
      { word: 'collar', tr: 'yaka' },
      { word: 'shorts', tr: 'şort' },
      { word: 'fabric', tr: 'kumaş' },
      { word: 'sweater', tr: 'kazak' },
      { word: 'uniform', tr: 'üniforma' },
      { word: 'pajamas', tr: 'pijama' },
      { word: 'sneaker', tr: 'spor ayakkabı' },
      { word: 'earring', tr: 'küpe' },
      { word: 'costume', tr: 'kostüm' },
      { word: 'leather', tr: 'deri (malzeme)' },
      { word: 'necklace', tr: 'kolye' },
      { word: 'bracelet', tr: 'bilezik' },
      { word: 'umbrella', tr: 'şemsiye' },
      { word: 'slippers', tr: 'terlik' },
      { word: 'backpack', tr: 'sırt çantası' },
    ],
  },

  {
    id: 'doga',
    name: 'Doğa & Hava',
    nameEn: 'Nature & Weather',
    icon: '🌿',
    blurb: 'Gökyüzü, deniz, dağ ve mevsimler',
    blurbEn: 'Sky, sea, mountains and seasons',
    words: [
      { word: 'sun', tr: 'güneş' },
      { word: 'sky', tr: 'gökyüzü' },
      { word: 'sea', tr: 'deniz' },
      { word: 'ice', tr: 'buz' },
      { word: 'fog', tr: 'sis' },
      { word: 'air', tr: 'hava' },
      { word: 'mud', tr: 'çamur' },
      { word: 'bay', tr: 'koy' },
      { word: 'hay', tr: 'saman' },
      { word: 'tree', tr: 'ağaç' },
      { word: 'rain', tr: 'yağmur' },
      { word: 'snow', tr: 'kar' },
      { word: 'wind', tr: 'rüzgar' },
      { word: 'star', tr: 'yıldız' },
      { word: 'moon', tr: 'ay' },
      { word: 'lake', tr: 'göl' },
      { word: 'hill', tr: 'tepe' },
      { word: 'rock', tr: 'kaya' },
      { word: 'sand', tr: 'kum' },
      { word: 'leaf', tr: 'yaprak' },
      { word: 'fire', tr: 'ateş' },
      { word: 'wave', tr: 'dalga' },
      { word: 'dust', tr: 'toz' },
      { word: 'seed', tr: 'tohum' },
      { word: 'bush', tr: 'çalı' },
      { word: 'dawn', tr: 'şafak' },
      { word: 'dusk', tr: 'alacakaranlık' },
      { word: 'mist', tr: 'pus' },
      { word: 'reef', tr: 'resif' },
      { word: 'cave', tr: 'mağara' },
      { word: 'cloud', tr: 'bulut' },
      { word: 'storm', tr: 'fırtına' },
      { word: 'river', tr: 'nehir' },
      { word: 'beach', tr: 'plaj' },
      { word: 'grass', tr: 'çimen' },
      { word: 'plant', tr: 'bitki' },
      { word: 'ocean', tr: 'okyanus' },
      { word: 'stone', tr: 'taş' },
      { word: 'field', tr: 'tarla' },
      { word: 'coast', tr: 'kıyı' },
      { word: 'shore', tr: 'sahil' },
      { word: 'frost', tr: 'ayaz' },
      { word: 'flame', tr: 'alev' },
      { word: 'marsh', tr: 'bataklık' },
      { word: 'creek', tr: 'dere' },
      { word: 'ridge', tr: 'sırt, bayır' },
      { word: 'earth', tr: 'yeryüzü' },
      { word: 'blaze', tr: 'yangın' },
      { word: 'forest', tr: 'orman' },
      { word: 'flower', tr: 'çiçek' },
      { word: 'valley', tr: 'vadi' },
      { word: 'desert', tr: 'çöl' },
      { word: 'island', tr: 'ada' },
      { word: 'jungle', tr: 'orman, cangıl' },
      { word: 'breeze', tr: 'esinti' },
      { word: 'meadow', tr: 'çayır' },
      { word: 'canyon', tr: 'kanyon' },
      { word: 'nature', tr: 'doğa' },
      { word: 'spring', tr: 'ilkbahar' },
      { word: 'autumn', tr: 'sonbahar' },
      { word: 'summer', tr: 'yaz' },
      { word: 'winter', tr: 'kış' },
      { word: 'season', tr: 'mevsim' },
      { word: 'sunset', tr: 'gün batımı' },
      { word: 'shadow', tr: 'gölge' },
      { word: 'planet', tr: 'gezegen' },
      { word: 'weather', tr: 'hava durumu' },
      { word: 'thunder', tr: 'gök gürültüsü' },
      { word: 'volcano', tr: 'yanardağ' },
      { word: 'glacier', tr: 'buzul' },
      { word: 'iceberg', tr: 'buzdağı' },
      { word: 'rainbow', tr: 'gökkuşağı' },
      { word: 'sunrise', tr: 'gün doğumu' },
      { word: 'mountain', tr: 'dağ' },
      { word: 'lightning', tr: 'şimşek' },
      { word: 'waterfall', tr: 'şelale' },
    ],
  },

  {
    id: 'sehir',
    name: 'Şehir & Yerler',
    nameEn: 'City & Places',
    icon: '🏙️',
    blurb: 'Sokaklar, binalar, gidilecek yerler',
    blurbEn: 'Streets, buildings, places to go',
    words: [
      { word: 'inn', tr: 'han, otel' },
      { word: 'zoo', tr: 'hayvanat bahçesi' },
      { word: 'bar', tr: 'bar' },
      { word: 'gym', tr: 'spor salonu' },
      { word: 'pub', tr: 'birahane' },
      { word: 'city', tr: 'şehir' },
      { word: 'town', tr: 'kasaba' },
      { word: 'road', tr: 'yol' },
      { word: 'shop', tr: 'dükkan' },
      { word: 'park', tr: 'park' },
      { word: 'cafe', tr: 'kafe' },
      { word: 'bank', tr: 'banka' },
      { word: 'mall', tr: 'alışveriş merkezi' },
      { word: 'farm', tr: 'çiftlik' },
      { word: 'hall', tr: 'salon' },
      { word: 'port', tr: 'liman' },
      { word: 'pool', tr: 'havuz' },
      { word: 'path', tr: 'patika' },
      { word: 'lane', tr: 'ara sokak' },
      { word: 'site', tr: 'alan, saha' },
      { word: 'store', tr: 'mağaza' },
      { word: 'hotel', tr: 'otel' },
      { word: 'plaza', tr: 'meydan' },
      { word: 'tower', tr: 'kule' },
      { word: 'court', tr: 'mahkeme' },
      { word: 'arena', tr: 'arena' },
      { word: 'cabin', tr: 'kulübe' },
      { word: 'villa', tr: 'villa' },
      { word: 'ranch', tr: 'çiftlik evi' },
      { word: 'motel', tr: 'motel' },
      { word: 'kiosk', tr: 'büfe' },
      { word: 'alley', tr: 'dar sokak' },
      { word: 'salon', tr: 'kuaför' },
      { word: 'bridge', tr: 'köprü' },
      { word: 'church', tr: 'kilise' },
      { word: 'garage', tr: 'garaj' },
      { word: 'market', tr: 'pazar' },
      { word: 'museum', tr: 'müze' },
      { word: 'office', tr: 'ofis' },
      { word: 'square', tr: 'meydan' },
      { word: 'street', tr: 'cadde' },
      { word: 'temple', tr: 'tapınak' },
      { word: 'bakery', tr: 'fırın (dükkan)' },
      { word: 'palace', tr: 'saray' },
      { word: 'prison', tr: 'hapishane' },
      { word: 'subway', tr: 'metro' },
      { word: 'tunnel', tr: 'tünel' },
      { word: 'castle', tr: 'kale' },
      { word: 'cinema', tr: 'sinema' },
      { word: 'garden', tr: 'bahçe' },
      { word: 'airport', tr: 'havaalanı' },
      { word: 'station', tr: 'istasyon' },
      { word: 'factory', tr: 'fabrika' },
      { word: 'gallery', tr: 'galeri' },
      { word: 'theater', tr: 'tiyatro' },
      { word: 'library', tr: 'kütüphane' },
      { word: 'stadium', tr: 'stadyum' },
      { word: 'village', tr: 'köy' },
      { word: 'country', tr: 'ülke' },
      { word: 'capital', tr: 'başkent' },
      { word: 'building', tr: 'bina' },
      { word: 'downtown', tr: 'şehir merkezi' },
      { word: 'monument', tr: 'anıt' },
      { word: 'boutique', tr: 'butik' },
    ],
  },

  {
    id: 'seyahat',
    name: 'Seyahat & Ulaşım',
    nameEn: 'Travel & Transport',
    icon: '✈️',
    blurb: 'Araçlar, yolculuk, tatil',
    blurbEn: 'Vehicles, journeys, holidays',
    words: [
      { word: 'bus', tr: 'otobüs' },
      { word: 'car', tr: 'araba' },
      { word: 'van', tr: 'minibüs' },
      { word: 'jet', tr: 'jet' },
      { word: 'map', tr: 'harita' },
      { word: 'gas', tr: 'benzin' },
      { word: 'bike', tr: 'bisiklet' },
      { word: 'boat', tr: 'tekne' },
      { word: 'ship', tr: 'gemi' },
      { word: 'taxi', tr: 'taksi' },
      { word: 'tram', tr: 'tramvay' },
      { word: 'ride', tr: 'yolculuk etmek' },
      { word: 'trip', tr: 'gezi' },
      { word: 'tour', tr: 'tur' },
      { word: 'sail', tr: 'yelken açmak' },
      { word: 'fare', tr: 'bilet ücreti' },
      { word: 'dock', tr: 'iskele' },
      { word: 'exit', tr: 'çıkış' },
      { word: 'lift', tr: 'asansör' },
      { word: 'plane', tr: 'uçak' },
      { word: 'train', tr: 'tren' },
      { word: 'truck', tr: 'kamyon' },
      { word: 'wheel', tr: 'tekerlek' },
      { word: 'ferry', tr: 'feribot' },
      { word: 'cargo', tr: 'kargo, yük' },
      { word: 'route', tr: 'güzergah' },
      { word: 'canoe', tr: 'kano' },
      { word: 'wagon', tr: 'vagon' },
      { word: 'pilot', tr: 'pilot' },
      { word: 'depot', tr: 'garaj, depo' },
      { word: 'visit', tr: 'ziyaret etmek' },
      { word: 'guide', tr: 'rehber' },
      { word: 'engine', tr: 'motor' },
      { word: 'ticket', tr: 'bilet' },
      { word: 'flight', tr: 'uçuş' },
      { word: 'driver', tr: 'sürücü' },
      { word: 'rocket', tr: 'roket' },
      { word: 'camper', tr: 'karavan' },
      { word: 'cruise', tr: 'gemi seyahati' },
      { word: 'saddle', tr: 'eyer' },
      { word: 'anchor', tr: 'çapa' },
      { word: 'runway', tr: 'pist' },
      { word: 'highway', tr: 'otoyol' },
      { word: 'luggage', tr: 'bagaj' },
      { word: 'journey', tr: 'yolculuk' },
      { word: 'traffic', tr: 'trafik' },
      { word: 'scooter', tr: 'scooter' },
      { word: 'holiday', tr: 'tatil' },
      { word: 'tourist', tr: 'turist' },
      { word: 'railway', tr: 'demiryolu' },
      { word: 'airline', tr: 'havayolu' },
      { word: 'airplane', tr: 'uçak' },
      { word: 'passport', tr: 'pasaport' },
      { word: 'suitcase', tr: 'valiz' },
      { word: 'sidewalk', tr: 'kaldırım' },
      { word: 'motorbike', tr: 'motosiklet' },
    ],
  },

  {
    id: 'okul',
    name: 'Okul & Eğitim',
    nameEn: 'School & Study',
    icon: '📚',
    blurb: 'Sınıf, ders, sınav ve kırtasiye',
    blurbEn: 'Classroom, lessons, exams and stationery',
    words: [
      { word: 'pen', tr: 'kalem' },
      { word: 'ink', tr: 'mürekkep' },
      { word: 'art', tr: 'sanat' },
      { word: 'book', tr: 'kitap' },
      { word: 'page', tr: 'sayfa' },
      { word: 'math', tr: 'matematik' },
      { word: 'quiz', tr: 'kısa sınav' },
      { word: 'test', tr: 'test' },
      { word: 'note', tr: 'not' },
      { word: 'exam', tr: 'sınav' },
      { word: 'word', tr: 'kelime' },
      { word: 'term', tr: 'dönem' },
      { word: 'rule', tr: 'kural' },
      { word: 'idea', tr: 'fikir' },
      { word: 'fact', tr: 'gerçek' },
      { word: 'text', tr: 'metin' },
      { word: 'class', tr: 'sınıf' },
      { word: 'paper', tr: 'kağıt' },
      { word: 'pupil', tr: 'öğrenci' },
      { word: 'chalk', tr: 'tebeşir' },
      { word: 'grade', tr: 'not, sınıf' },
      { word: 'essay', tr: 'kompozisyon' },
      { word: 'board', tr: 'tahta' },
      { word: 'study', tr: 'çalışmak' },
      { word: 'learn', tr: 'öğrenmek' },
      { word: 'write', tr: 'yazmak' },
      { word: 'tutor', tr: 'özel öğretmen' },
      { word: 'ruler', tr: 'cetvel' },
      { word: 'topic', tr: 'konu' },
      { word: 'basic', tr: 'temel' },
      { word: 'eraser', tr: 'silgi' },
      { word: 'lesson', tr: 'ders' },
      { word: 'school', tr: 'okul' },
      { word: 'pencil', tr: 'kurşun kalem' },
      { word: 'course', tr: 'kurs' },
      { word: 'degree', tr: 'derece, diploma' },
      { word: 'letter', tr: 'harf, mektup' },
      { word: 'answer', tr: 'cevap' },
      { word: 'report', tr: 'rapor' },
      { word: 'campus', tr: 'kampüs' },
      { word: 'theory', tr: 'teori' },
      { word: 'result', tr: 'sonuç' },
      { word: 'method', tr: 'yöntem' },
      { word: 'teacher', tr: 'öğretmen' },
      { word: 'student', tr: 'öğrenci' },
      { word: 'science', tr: 'bilim' },
      { word: 'history', tr: 'tarih' },
      { word: 'diploma', tr: 'diploma' },
      { word: 'physics', tr: 'fizik' },
      { word: 'biology', tr: 'biyoloji' },
      { word: 'example', tr: 'örnek' },
      { word: 'meaning', tr: 'anlam' },
      { word: 'notebook', tr: 'defter' },
      { word: 'question', tr: 'soru' },
      { word: 'homework', tr: 'ev ödevi' },
      { word: 'chemistry', tr: 'kimya' },
      { word: 'geography', tr: 'coğrafya' },
      { word: 'classroom', tr: 'derslik' },
      { word: 'education', tr: 'eğitim' },
      { word: 'knowledge', tr: 'bilgi' },
    ],
  },

  {
    id: 'is',
    name: 'İş & Meslekler',
    nameEn: 'Work & Jobs',
    icon: '💼',
    blurb: 'Meslekler, para ve iş hayatı',
    blurbEn: 'Professions, money and working life',
    words: [
      { word: 'job', tr: 'iş' },
      { word: 'pay', tr: 'ödemek' },
      { word: 'fee', tr: 'ücret' },
      { word: 'tax', tr: 'vergi' },
      { word: 'work', tr: 'çalışmak' },
      { word: 'team', tr: 'takım' },
      { word: 'task', tr: 'görev' },
      { word: 'plan', tr: 'plan' },
      { word: 'sale', tr: 'satış' },
      { word: 'deal', tr: 'anlaşma' },
      { word: 'cash', tr: 'nakit' },
      { word: 'chef', tr: 'aşçı' },
      { word: 'hire', tr: 'işe almak' },
      { word: 'wage', tr: 'ücret' },
      { word: 'firm', tr: 'firma' },
      { word: 'debt', tr: 'borç' },
      { word: 'role', tr: 'rol' },
      { word: 'boss', tr: 'patron' },
      { word: 'cost', tr: 'maliyet' },
      { word: 'money', tr: 'para' },
      { word: 'staff', tr: 'personel' },
      { word: 'offer', tr: 'teklif' },
      { word: 'price', tr: 'fiyat' },
      { word: 'brand', tr: 'marka' },
      { word: 'agent', tr: 'temsilci' },
      { word: 'buyer', tr: 'alıcı' },
      { word: 'skill', tr: 'beceri' },
      { word: 'trade', tr: 'ticaret' },
      { word: 'actor', tr: 'oyuncu' },
      { word: 'baker', tr: 'fırıncı' },
      { word: 'guard', tr: 'güvenlik görevlisi' },
      { word: 'judge', tr: 'hakim' },
      { word: 'clerk', tr: 'memur' },
      { word: 'profit', tr: 'kâr' },
      { word: 'worker', tr: 'işçi' },
      { word: 'career', tr: 'kariyer' },
      { word: 'income', tr: 'gelir' },
      { word: 'budget', tr: 'bütçe' },
      { word: 'client', tr: 'müşteri' },
      { word: 'salary', tr: 'maaş' },
      { word: 'tailor', tr: 'terzi' },
      { word: 'waiter', tr: 'garson' },
      { word: 'artist', tr: 'sanatçı' },
      { word: 'singer', tr: 'şarkıcı' },
      { word: 'lawyer', tr: 'avukat' },
      { word: 'farmer', tr: 'çiftçi' },
      { word: 'barber', tr: 'berber' },
      { word: 'dancer', tr: 'dansçı' },
      { word: 'writer', tr: 'yazar' },
      { word: 'manager', tr: 'müdür' },
      { word: 'company', tr: 'şirket' },
      { word: 'cashier', tr: 'kasiyer' },
      { word: 'builder', tr: 'inşaatçı' },
      { word: 'painter', tr: 'ressam' },
      { word: 'plumber', tr: 'tesisatçı' },
      { word: 'soldier', tr: 'asker' },
      { word: 'meeting', tr: 'toplantı' },
      { word: 'contract', tr: 'sözleşme' },
      { word: 'engineer', tr: 'mühendis' },
      { word: 'business', tr: 'iş, ticaret' },
      { word: 'employee', tr: 'çalışan' },
      { word: 'mechanic', tr: 'tamirci' },
      { word: 'designer', tr: 'tasarımcı' },
      { word: 'reporter', tr: 'muhabir' },
      { word: 'musician', tr: 'müzisyen' },
      { word: 'director', tr: 'yönetmen' },
      { word: 'customer', tr: 'müşteri' },
    ],
  },

  {
    id: 'zaman',
    name: 'Zaman & Ölçü',
    nameEn: 'Time & Measure',
    icon: '⏰',
    blurb: 'Saatler, günler, ölçüler',
    blurbEn: 'Hours, days, measurements',
    words: [
      { word: 'age', tr: 'yaş' },
      { word: 'day', tr: 'gün' },
      { word: 'ago', tr: 'önce' },
      { word: 'hour', tr: 'saat' },
      { word: 'week', tr: 'hafta' },
      { word: 'year', tr: 'yıl' },
      { word: 'time', tr: 'zaman' },
      { word: 'noon', tr: 'öğlen' },
      { word: 'date', tr: 'tarih' },
      { word: 'past', tr: 'geçmiş' },
      { word: 'next', tr: 'sonraki' },
      { word: 'soon', tr: 'yakında' },
      { word: 'late', tr: 'geç' },
      { word: 'once', tr: 'bir kez' },
      { word: 'half', tr: 'yarım' },
      { word: 'inch', tr: 'inç' },
      { word: 'mile', tr: 'mil' },
      { word: 'size', tr: 'boyut' },
      { word: 'pair', tr: 'çift' },
      { word: 'month', tr: 'ay (takvim)' },
      { word: 'today', tr: 'bugün' },
      { word: 'night', tr: 'gece' },
      { word: 'first', tr: 'birinci' },
      { word: 'third', tr: 'üçüncü' },
      { word: 'early', tr: 'erken' },
      { word: 'daily', tr: 'günlük' },
      { word: 'dozen', tr: 'düzine' },
      { word: 'depth', tr: 'derinlik' },
      { word: 'liter', tr: 'litre' },
      { word: 'meter', tr: 'metre' },
      { word: 'ounce', tr: 'ons' },
      { word: 'total', tr: 'toplam' },
      { word: 'count', tr: 'saymak' },
      { word: 'never', tr: 'asla' },
      { word: 'minute', tr: 'dakika' },
      { word: 'second', tr: 'saniye' },
      { word: 'decade', tr: 'on yıl' },
      { word: 'always', tr: 'her zaman' },
      { word: 'before', tr: 'önce' },
      { word: 'weekly', tr: 'haftalık' },
      { word: 'height', tr: 'yükseklik' },
      { word: 'weight', tr: 'ağırlık' },
      { word: 'length', tr: 'uzunluk' },
      { word: 'amount', tr: 'miktar' },
      { word: 'number', tr: 'sayı' },
      { word: 'double', tr: 'iki kat' },
      { word: 'morning', tr: 'sabah' },
      { word: 'evening', tr: 'akşam' },
      { word: 'tonight', tr: 'bu gece' },
      { word: 'century', tr: 'yüzyıl' },
      { word: 'weekend', tr: 'hafta sonu' },
      { word: 'monthly', tr: 'aylık' },
      { word: 'quarter', tr: 'çeyrek' },
      { word: 'measure', tr: 'ölçmek' },
      { word: 'average', tr: 'ortalama' },
      { word: 'calendar', tr: 'takvim' },
      { word: 'tomorrow', tr: 'yarın' },
      { word: 'midnight', tr: 'gece yarısı' },
      { word: 'birthday', tr: 'doğum günü' },
      { word: 'schedule', tr: 'program, çizelge' },
      { word: 'yesterday', tr: 'dün' },
    ],
  },

  {
    id: 'spor',
    name: 'Spor & Hobiler',
    nameEn: 'Sports & Hobbies',
    icon: '⚽',
    blurb: 'Oyunlar, müzik, boş zaman',
    blurbEn: 'Games, music, free time',
    words: [
      { word: 'win', tr: 'kazanmak' },
      { word: 'ski', tr: 'kayak yapmak' },
      { word: 'net', tr: 'file, ağ' },
      { word: 'toy', tr: 'oyuncak' },
      { word: 'bow', tr: 'yay' },
      { word: 'game', tr: 'oyun' },
      { word: 'ball', tr: 'top' },
      { word: 'goal', tr: 'gol' },
      { word: 'swim', tr: 'yüzmek' },
      { word: 'race', tr: 'yarış' },
      { word: 'jump', tr: 'zıplamak' },
      { word: 'club', tr: 'kulüp' },
      { word: 'golf', tr: 'golf' },
      { word: 'dive', tr: 'dalmak' },
      { word: 'kick', tr: 'tekme atmak' },
      { word: 'hike', tr: 'doğa yürüyüşü' },
      { word: 'judo', tr: 'judo' },
      { word: 'card', tr: 'kart' },
      { word: 'match', tr: 'maç' },
      { word: 'score', tr: 'skor' },
      { word: 'sport', tr: 'spor' },
      { word: 'medal', tr: 'madalya' },
      { word: 'rugby', tr: 'ragbi' },
      { word: 'skate', tr: 'paten' },
      { word: 'dance', tr: 'dans' },
      { word: 'music', tr: 'müzik' },
      { word: 'movie', tr: 'film' },
      { word: 'party', tr: 'parti' },
      { word: 'hobby', tr: 'hobi' },
      { word: 'chess', tr: 'satranç' },
      { word: 'piano', tr: 'piyano' },
      { word: 'drums', tr: 'davul' },
      { word: 'flute', tr: 'flüt' },
      { word: 'prize', tr: 'ödül' },
      { word: 'coach', tr: 'antrenör' },
      { word: 'arrow', tr: 'ok' },
      { word: 'tennis', tr: 'tenis' },
      { word: 'soccer', tr: 'futbol' },
      { word: 'boxing', tr: 'boks' },
      { word: 'hockey', tr: 'hokey' },
      { word: 'runner', tr: 'koşucu' },
      { word: 'winner', tr: 'kazanan' },
      { word: 'player', tr: 'oyuncu' },
      { word: 'racket', tr: 'raket' },
      { word: 'trophy', tr: 'kupa' },
      { word: 'hiking', tr: 'doğa yürüyüşü' },
      { word: 'puzzle', tr: 'bulmaca' },
      { word: 'guitar', tr: 'gitar' },
      { word: 'violin', tr: 'keman' },
      { word: 'cycling', tr: 'bisiklet sürme' },
      { word: 'fitness', tr: 'fitness' },
      { word: 'referee', tr: 'hakem' },
      { word: 'workout', tr: 'antrenman' },
      { word: 'jogging', tr: 'hafif koşu' },
      { word: 'archery', tr: 'okçuluk' },
      { word: 'reading', tr: 'okuma' },
      { word: 'singing', tr: 'şarkı söyleme' },
      { word: 'camping', tr: 'kamp' },
      { word: 'fishing', tr: 'balık tutma' },
      { word: 'cooking', tr: 'yemek pişirme' },
      { word: 'drawing', tr: 'çizim' },
      { word: 'concert', tr: 'konser' },
      { word: 'baseball', tr: 'beyzbol' },
      { word: 'football', tr: 'futbol' },
      { word: 'swimming', tr: 'yüzme' },
      { word: 'marathon', tr: 'maraton' },
      { word: 'exercise', tr: 'egzersiz' },
      { word: 'champion', tr: 'şampiyon' },
      { word: 'climbing', tr: 'tırmanış' },
      { word: 'painting', tr: 'resim yapma' },
    ],
  },

  {
    id: 'teknoloji',
    name: 'Teknoloji',
    nameEn: 'Technology',
    icon: '💻',
    blurb: 'Bilgisayar, internet, cihazlar',
    blurbEn: 'Computers, internet, devices',
    words: [
      { word: 'app', tr: 'uygulama' },
      { word: 'web', tr: 'internet' },
      { word: 'chip', tr: 'çip' },
      { word: 'data', tr: 'veri' },
      { word: 'code', tr: 'kod' },
      { word: 'file', tr: 'dosya' },
      { word: 'link', tr: 'bağlantı' },
      { word: 'disk', tr: 'disk' },
      { word: 'menu', tr: 'menü' },
      { word: 'user', tr: 'kullanıcı' },
      { word: 'mail', tr: 'posta' },
      { word: 'wifi', tr: 'kablosuz ağ' },
      { word: 'byte', tr: 'bayt' },
      { word: 'chat', tr: 'sohbet' },
      { word: 'blog', tr: 'blog' },
      { word: 'icon', tr: 'simge' },
      { word: 'save', tr: 'kaydetmek' },
      { word: 'plug', tr: 'fiş' },
      { word: 'wire', tr: 'kablo' },
      { word: 'email', tr: 'e-posta' },
      { word: 'phone', tr: 'telefon' },
      { word: 'video', tr: 'video' },
      { word: 'cable', tr: 'kablo' },
      { word: 'robot', tr: 'robot' },
      { word: 'pixel', tr: 'piksel' },
      { word: 'modem', tr: 'modem' },
      { word: 'login', tr: 'oturum açma' },
      { word: 'click', tr: 'tıklamak' },
      { word: 'share', tr: 'paylaşmak' },
      { word: 'photo', tr: 'fotoğraf' },
      { word: 'radio', tr: 'radyo' },
      { word: 'media', tr: 'medya' },
      { word: 'drone', tr: 'drone' },
      { word: 'laptop', tr: 'dizüstü bilgisayar' },
      { word: 'screen', tr: 'ekran' },
      { word: 'camera', tr: 'kamera' },
      { word: 'device', tr: 'cihaz' },
      { word: 'memory', tr: 'bellek' },
      { word: 'folder', tr: 'klasör' },
      { word: 'online', tr: 'çevrimiçi' },
      { word: 'server', tr: 'sunucu' },
      { word: 'system', tr: 'sistem' },
      { word: 'upload', tr: 'yüklemek' },
      { word: 'backup', tr: 'yedek' },
      { word: 'mobile', tr: 'mobil' },
      { word: 'gadget', tr: 'aygıt' },
      { word: 'sensor', tr: 'sensör' },
      { word: 'signal', tr: 'sinyal' },
      { word: 'update', tr: 'güncelleme' },
      { word: 'printer', tr: 'yazıcı' },
      { word: 'network', tr: 'ağ' },
      { word: 'digital', tr: 'dijital' },
      { word: 'monitor', tr: 'monitör' },
      { word: 'browser', tr: 'tarayıcı' },
      { word: 'machine', tr: 'makine' },
      { word: 'battery', tr: 'pil' },
      { word: 'charger', tr: 'şarj aleti' },
      { word: 'desktop', tr: 'masaüstü' },
      { word: 'program', tr: 'program' },
      { word: 'account', tr: 'hesap' },
      { word: 'antenna', tr: 'anten' },
      { word: 'computer', tr: 'bilgisayar' },
      { word: 'keyboard', tr: 'klavye' },
      { word: 'internet', tr: 'internet' },
      { word: 'software', tr: 'yazılım' },
      { word: 'hardware', tr: 'donanım' },
      { word: 'download', tr: 'indirmek' },
      { word: 'password', tr: 'şifre' },
      { word: 'wireless', tr: 'kablosuz' },
    ],
  },

  {
    id: 'duygular',
    name: 'Duygular & Kişilik',
    nameEn: 'Emotions & Personality',
    icon: '😊',
    blurb: 'Hisler, huylar, karakter',
    blurbEn: 'Feelings, moods, character',
    words: [
      { word: 'shy', tr: 'utangaç' },
      { word: 'joy', tr: 'neşe' },
      { word: 'fun', tr: 'eğlence' },
      { word: 'sad', tr: 'üzgün' },
      { word: 'mad', tr: 'kızgın' },
      { word: 'calm', tr: 'sakin' },
      { word: 'kind', tr: 'nazik' },
      { word: 'glad', tr: 'memnun' },
      { word: 'fear', tr: 'korku' },
      { word: 'hope', tr: 'umut' },
      { word: 'love', tr: 'sevgi' },
      { word: 'rude', tr: 'kaba' },
      { word: 'wise', tr: 'bilge' },
      { word: 'bold', tr: 'cesur' },
      { word: 'cute', tr: 'sevimli' },
      { word: 'dear', tr: 'sevgili' },
      { word: 'envy', tr: 'kıskançlık' },
      { word: 'hate', tr: 'nefret' },
      { word: 'pity', tr: 'acıma' },
      { word: 'mood', tr: 'ruh hali' },
      { word: 'happy', tr: 'mutlu' },
      { word: 'angry', tr: 'öfkeli' },
      { word: 'proud', tr: 'gururlu' },
      { word: 'brave', tr: 'cesur' },
      { word: 'quiet', tr: 'sessiz' },
      { word: 'funny', tr: 'komik' },
      { word: 'smart', tr: 'akıllı' },
      { word: 'sorry', tr: 'üzgün' },
      { word: 'upset', tr: 'keyfi kaçmış' },
      { word: 'alone', tr: 'yalnız' },
      { word: 'eager', tr: 'istekli' },
      { word: 'moody', tr: 'huysuz' },
      { word: 'tense', tr: 'gergin' },
      { word: 'trust', tr: 'güven' },
      { word: 'laugh', tr: 'gülmek' },
      { word: 'smile', tr: 'gülümsemek' },
      { word: 'cheer', tr: 'neşelendirmek' },
      { word: 'shame', tr: 'utanç' },
      { word: 'lonely', tr: 'yalnız' },
      { word: 'polite', tr: 'kibar' },
      { word: 'gentle', tr: 'yumuşak huylu' },
      { word: 'honest', tr: 'dürüst' },
      { word: 'clever', tr: 'zeki' },
      { word: 'joyful', tr: 'neşeli' },
      { word: 'sorrow', tr: 'keder' },
      { word: 'temper', tr: 'huy, öfke' },
      { word: 'caring', tr: 'ilgili, şefkatli' },
      { word: 'hungry', tr: 'aç' },
      { word: 'sleepy', tr: 'uykulu' },
      { word: 'boring', tr: 'sıkıcı' },
      { word: 'lively', tr: 'canlı' },
      { word: 'humble', tr: 'alçakgönüllü' },
      { word: 'stress', tr: 'stres' },
      { word: 'nervous', tr: 'gergin' },
      { word: 'anxious', tr: 'endişeli' },
      { word: 'excited', tr: 'heyecanlı' },
      { word: 'curious', tr: 'meraklı' },
      { word: 'jealous', tr: 'kıskanç' },
      { word: 'relaxed', tr: 'rahatlamış' },
      { word: 'worried', tr: 'endişeli' },
      { word: 'sadness', tr: 'üzüntü' },
      { word: 'respect', tr: 'saygı' },
      { word: 'courage', tr: 'cesaret' },
      { word: 'friendly', tr: 'arkadaş canlısı' },
      { word: 'generous', tr: 'cömert' },
      { word: 'grateful', tr: 'minnettar' },
      { word: 'patience', tr: 'sabır' },
      { word: 'kindness', tr: 'nezaket' },
      { word: 'thankful', tr: 'müteşekkir' },
      { word: 'confident', tr: 'kendine güvenen' },
    ],
  },

  {
    id: 'fiiller',
    name: 'Fiiller',
    nameEn: 'Verbs',
    icon: '🏃',
    blurb: 'Günlük hayatın eylemleri',
    blurbEn: 'The actions of everyday life',
    words: [
      { word: 'eat', tr: 'yemek' },
      { word: 'run', tr: 'koşmak' },
      { word: 'see', tr: 'görmek' },
      { word: 'buy', tr: 'satın almak' },
      { word: 'cut', tr: 'kesmek' },
      { word: 'fly', tr: 'uçmak' },
      { word: 'sit', tr: 'oturmak' },
      { word: 'ask', tr: 'sormak' },
      { word: 'put', tr: 'koymak' },
      { word: 'get', tr: 'almak' },
      { word: 'add', tr: 'eklemek' },
      { word: 'mix', tr: 'karıştırmak' },
      { word: 'dig', tr: 'kazmak' },
      { word: 'hug', tr: 'sarılmak' },
      { word: 'say', tr: 'söylemek' },
      { word: 'try', tr: 'denemek' },
      { word: 'use', tr: 'kullanmak' },
      { word: 'read', tr: 'okumak' },
      { word: 'walk', tr: 'yürümek' },
      { word: 'talk', tr: 'konuşmak' },
      { word: 'open', tr: 'açmak' },
      { word: 'help', tr: 'yardım etmek' },
      { word: 'stop', tr: 'durmak' },
      { word: 'come', tr: 'gelmek' },
      { word: 'give', tr: 'vermek' },
      { word: 'take', tr: 'almak' },
      { word: 'make', tr: 'yapmak' },
      { word: 'find', tr: 'bulmak' },
      { word: 'look', tr: 'bakmak' },
      { word: 'feel', tr: 'hissetmek' },
      { word: 'hear', tr: 'duymak' },
      { word: 'hold', tr: 'tutmak' },
      { word: 'keep', tr: 'saklamak' },
      { word: 'live', tr: 'yaşamak' },
      { word: 'meet', tr: 'tanışmak' },
      { word: 'move', tr: 'hareket etmek' },
      { word: 'play', tr: 'oynamak' },
      { word: 'pull', tr: 'çekmek' },
      { word: 'push', tr: 'itmek' },
      { word: 'sell', tr: 'satmak' },
      { word: 'send', tr: 'göndermek' },
      { word: 'show', tr: 'göstermek' },
      { word: 'sing', tr: 'şarkı söylemek' },
      { word: 'stay', tr: 'kalmak' },
      { word: 'turn', tr: 'dönmek' },
      { word: 'wait', tr: 'beklemek' },
      { word: 'wash', tr: 'yıkamak' },
      { word: 'wear', tr: 'giymek' },
      { word: 'grow', tr: 'büyümek' },
      { word: 'wake', tr: 'uyanmak' },
      { word: 'cook', tr: 'yemek pişirmek' },
      { word: 'draw', tr: 'çizmek' },
      { word: 'call', tr: 'aramak' },
      { word: 'fall', tr: 'düşmek' },
      { word: 'lose', tr: 'kaybetmek' },
      { word: 'pick', tr: 'seçmek' },
      { word: 'join', tr: 'katılmak' },
      { word: 'earn', tr: 'kazanmak' },
      { word: 'sleep', tr: 'uyumak' },
      { word: 'drink', tr: 'içmek' },
      { word: 'speak', tr: 'konuşmak' },
      { word: 'break', tr: 'kırmak' },
      { word: 'bring', tr: 'getirmek' },
      { word: 'build', tr: 'inşa etmek' },
      { word: 'catch', tr: 'yakalamak' },
      { word: 'paint', tr: 'boyamak' },
      { word: 'close', tr: 'kapatmak' },
      { word: 'dream', tr: 'rüya görmek' },
      { word: 'drive', tr: 'araba sürmek' },
      { word: 'enjoy', tr: 'keyif almak' },
      { word: 'leave', tr: 'ayrılmak' },
      { word: 'stand', tr: 'ayakta durmak' },
      { word: 'shout', tr: 'bağırmak' },
      { word: 'start', tr: 'başlamak' },
      { word: 'teach', tr: 'öğretmek' },
      { word: 'think', tr: 'düşünmek' },
      { word: 'throw', tr: 'atmak' },
      { word: 'touch', tr: 'dokunmak' },
      { word: 'watch', tr: 'izlemek' },
      { word: 'listen', tr: 'dinlemek' },
      { word: 'choose', tr: 'seçmek' },
      { word: 'follow', tr: 'takip etmek' },
      { word: 'forget', tr: 'unutmak' },
      { word: 'happen', tr: 'olmak, gerçekleşmek' },
      { word: 'repeat', tr: 'tekrarlamak' },
      { word: 'search', tr: 'aramak' },
      { word: 'travel', tr: 'seyahat etmek' },
      { word: 'become', tr: 'olmak' },
      { word: 'borrow', tr: 'ödünç almak' },
      { word: 'decide', tr: 'karar vermek' },
      { word: 'explain', tr: 'açıklamak' },
      { word: 'imagine', tr: 'hayal etmek' },
      { word: 'promise', tr: 'söz vermek' },
      { word: 'believe', tr: 'inanmak' },
      { word: 'prepare', tr: 'hazırlamak' },
      { word: 'discover', tr: 'keşfetmek' },
      { word: 'remember', tr: 'hatırlamak' },
      { word: 'continue', tr: 'devam etmek' },
    ],
  },

  {
    id: 'sifatlar',
    name: 'Sıfatlar & Renkler',
    nameEn: 'Adjectives & Colors',
    icon: '🎨',
    blurb: 'Nitelikler, renkler, karşıtlar',
    blurbEn: 'Qualities, colors, opposites',
    words: [
      { word: 'red', tr: 'kırmızı' },
      { word: 'hot', tr: 'sıcak' },
      { word: 'new', tr: 'yeni' },
      { word: 'old', tr: 'eski' },
      { word: 'dry', tr: 'kuru' },
      { word: 'wet', tr: 'ıslak' },
      { word: 'low', tr: 'alçak' },
      { word: 'far', tr: 'uzak' },
      { word: 'big', tr: 'büyük' },
      { word: 'raw', tr: 'çiğ' },
      { word: 'fit', tr: 'formda' },
      { word: 'blue', tr: 'mavi' },
      { word: 'pink', tr: 'pembe' },
      { word: 'gray', tr: 'gri' },
      { word: 'gold', tr: 'altın rengi' },
      { word: 'cold', tr: 'soğuk' },
      { word: 'warm', tr: 'ılık' },
      { word: 'good', tr: 'iyi' },
      { word: 'easy', tr: 'kolay' },
      { word: 'hard', tr: 'zor' },
      { word: 'fast', tr: 'hızlı' },
      { word: 'slow', tr: 'yavaş' },
      { word: 'tall', tr: 'uzun boylu' },
      { word: 'deep', tr: 'derin' },
      { word: 'wide', tr: 'geniş' },
      { word: 'rich', tr: 'zengin' },
      { word: 'poor', tr: 'fakir' },
      { word: 'soft', tr: 'yumuşak' },
      { word: 'loud', tr: 'gürültülü' },
      { word: 'dark', tr: 'karanlık' },
      { word: 'pale', tr: 'solgun' },
      { word: 'tidy', tr: 'düzenli' },
      { word: 'safe', tr: 'güvenli' },
      { word: 'sour', tr: 'ekşi' },
      { word: 'ripe', tr: 'olgun' },
      { word: 'thin', tr: 'ince' },
      { word: 'free', tr: 'özgür, bedava' },
      { word: 'real', tr: 'gerçek' },
      { word: 'full', tr: 'dolu' },
      { word: 'green', tr: 'yeşil' },
      { word: 'black', tr: 'siyah' },
      { word: 'white', tr: 'beyaz' },
      { word: 'brown', tr: 'kahverengi' },
      { word: 'large', tr: 'büyük' },
      { word: 'small', tr: 'küçük' },
      { word: 'short', tr: 'kısa' },
      { word: 'quick', tr: 'çabuk' },
      { word: 'clean', tr: 'temiz' },
      { word: 'dirty', tr: 'kirli' },
      { word: 'heavy', tr: 'ağır' },
      { word: 'light', tr: 'hafif' },
      { word: 'sweet', tr: 'tatlı' },
      { word: 'fresh', tr: 'taze' },
      { word: 'sharp', tr: 'keskin' },
      { word: 'rough', tr: 'pürüzlü' },
      { word: 'young', tr: 'genç' },
      { word: 'empty', tr: 'boş' },
      { word: 'plain', tr: 'sade' },
      { word: 'thick', tr: 'kalın' },
      { word: 'tight', tr: 'sıkı' },
      { word: 'sunny', tr: 'güneşli' },
      { word: 'windy', tr: 'rüzgarlı' },
      { word: 'noisy', tr: 'gürültülü' },
      { word: 'purple', tr: 'mor' },
      { word: 'frozen', tr: 'donmuş' },
      { word: 'silver', tr: 'gümüş rengi' },
      { word: 'yellow', tr: 'sarı' },
      { word: 'strong', tr: 'güçlü' },
      { word: 'pretty', tr: 'güzel' },
      { word: 'bright', tr: 'parlak' },
      { word: 'narrow', tr: 'dar' },
      { word: 'simple', tr: 'basit' },
      { word: 'modern', tr: 'modern' },
      { word: 'famous', tr: 'ünlü' },
      { word: 'silent', tr: 'sessiz' },
      { word: 'sudden', tr: 'ani' },
      { word: 'common', tr: 'yaygın' },
      { word: 'cloudy', tr: 'bulutlu' },
      { word: 'bitter', tr: 'acı' },
      { word: 'smooth', tr: 'pürüzsüz' },
      { word: 'wealthy', tr: 'varlıklı' },
      { word: 'healthy', tr: 'sağlıklı' },
      { word: 'crowded', tr: 'kalabalık' },
      { word: 'perfect', tr: 'mükemmel' },
      { word: 'serious', tr: 'ciddi' },
      { word: 'careful', tr: 'dikkatli' },
      { word: 'natural', tr: 'doğal' },
      { word: 'popular', tr: 'popüler' },
      { word: 'special', tr: 'özel' },
      { word: 'similar', tr: 'benzer' },
      { word: 'ancient', tr: 'antik' },
      { word: 'colorful', tr: 'renkli' },
      { word: 'powerful', tr: 'güçlü' },
      { word: 'terrible', tr: 'korkunç' },
      { word: 'valuable', tr: 'değerli' },
      { word: 'dangerous', tr: 'tehlikeli' },
      { word: 'expensive', tr: 'pahalı' },
      { word: 'beautiful', tr: 'güzel' },
      { word: 'important', tr: 'önemli' },
    ],
  },
];

/** Tüm paketlerin kelimeleri, paket sırasıyla düzleştirilmiş. */
export const ALL_WORDS: WordEntry[] = WORD_PACKS.flatMap((p) => p.words);

export const TOTAL_WORDS = ALL_WORDS.length;
export const TOTAL_PACKS = WORD_PACKS.length;
